# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Highland Paranormal Society
email: nathantreme@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Do not fear, explore.
url: "https://focused-sinoussi-5febc4.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl:               ''
icon: assets/images/about_logo_doodad.png
twitter_username: natetreme

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/page/:num/"

include: ['_pages']

show_excerpts: true
